export const SkillsList = [
  "HTML",
  "CSS/SASS/SCSS",
  "Vanilla js",
  "Node.JS",
  "React.JS",
  "Redux Toolkit",
  "MongoDB",
  "PostgreSQL",
  "Three.js",
  "React Three Fiber",
  "React Three Drei",
  "Blender",
  "TailwindCSS",
  "Material UI",
  "SVG Animation",
  "Pixel Perfect",
  "Git",
  "Responsive",
  "Mobile First",
  "Figma",
  "Adobe Photoshop",
  "Adobe Premiere Pro",
];
